version: "3.8"

services:
  #Postgres Services
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Tingeso_Entrega1
    ports:
      - "5432:5432"
    networks:
      - backend-network

  # Frontend services
  frontend1:
    image: arenht/frontend_entrega1:latest
    networks:
      - frontend-network

  frontend2:
    image: arenht/frontend_entrega1:latest
    networks:
      - frontend-network

  frontend3:
    image: arenht/frontend_entrega1:latest
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: arenht/backend_entrega1:latest
    environment:
      - DB_HOST=postgres
    networks:
      - backend-network
    depends_on:
      - postgres

  backend2:
    image: arenht/backend_entrega1:latest
    environment:
      - DB_HOST=postgres
    networks:
      - backend-network
    depends_on:
      - postgres

  backend3:
    image: arenht/backend_entrega1:latest
    environment:
      - DB_HOST=postgres
    networks:
      - backend-network
    depends_on:
      - postgres

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge