pipeline {
    agent any
    tools {
        maven 'maven_3_8_1'
        jdk 'jdk_17'
    }
    stages {
        stage('Build maven') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Arenht15/Tingeso-Entrega-Monolitica']])
                dir('Tingeso_Entrega1/Tingeso_Entrega1') { // Cambia a la carpeta 'backend'
                    bat 'mvn clean package' // Ejecuta Maven en la subcarpeta
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('Tingeso_Entrega1/Tingeso_Entrega1') { // Cambia a la carpeta 'backend' donde está el pom.xml
                    bat 'mvn test' // Ejecuta las pruebas unitarias
                }
            }
        }

        stage('Build docker image') {
            steps {
                script {
                    dir('Tingeso_Entrega1/Tingeso_Entrega1') { // Cambia a la carpeta 'backend' para construir la imagen Docker
                        bat 'docker build -t arenht/backend_entrega1:latest .' // Construye la imagen en la subcarpeta
                    }
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'tingeso1', variable: 'dhpsw')]) {
                        bat 'docker login -u arenht -p angelartista'
                    }
                    bat 'docker push arenht/backend_entrega1:latest' // Empuja la imagen a Docker Hub
                }
            }
        }
    }
}